
version: '2'

services:
  mongodb-primary:
    image: 'bitnami/mongodb:3.6.11'
    ports:
    - "27017:27017"
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_REPLICA_SET_NAME=replicat
    volumes:
      - 'mongodb_master_data:/bitnami'
    networks:
      - replicat-nw

  mongodb-secondary:
    image: 'bitnami/mongodb:3.6.11'
    ports:
    - "27018:27017"
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_REPLICA_SET_NAME=replicat
    volumes:
      - 'mongodb_secondary_data:/bitnami'
    networks:
      - replicat-nw

  mongodb-arbiter:
    image: 'bitnami/mongodb:3.6.11'
    ports:
    - "27019:27017"
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_REPLICA_SET_NAME=replicat
    networks:
      - replicat-nw

volumes:
  mongodb_master_data:
    driver: local
  mongodb_secondary_data:
    driver: local

networks:
  replicat-nw: